# times single query is run.
RESAMPLING_COUNT = 1
# TAVILY Search Results Count
MAX_RESULTS=3

# WEB page retrieval
CHUNK_SIZE=2000
CHUNK_OVERLAP=500    
TOP_K_WEB_PAGES = 5

# PROMPT SUMMARIZATION
KEEP_LAST_N = 4